[Feat/week1] xml 필수과제
NOW-SOPT-ANDROID/hyoeun-joo pull request #2
Opened 2024-04-03 20:59 UTC by hyoeunjoo

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #1  

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- LoginActivity

- 회원가입 버튼 추가
- 비밀번호 InputType 활용해서 가리기
- 회원가입 버튼 누르면 회원가입 (SignUpActivity)로 이동
- SignUpActivity로부터 받은 ID,PW와 일치하는 정보인지 확인후 MainActivity로 이동

- SignUpActivity

- ID 6~8자, PW 8~12자, name 공백불가 +한글자 이상 , mbti 
- 모든 조건 충족시 메인 화면 (MainActivity)로 이동
- Activity간의 입력 데이터 이동

-MainActivity

-SignUpActivity에서 받은 정보들을 보여줌
 
## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/hyoeun-joo/assets/137873124/8289f637-beaa-4e2b-99e1-ea0cfc934286

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
-아.. 부족한 실력이지만 최선을 다해봤습니다
-코리 할 부분이 정말 정말 많을텐데 남겨주시면 공부 열심히 해보겠습니다

2024-04-03 21:53 UTC, chattymin reviewed
뭔데 이 와비.
코드 깔끔 그잡채.

2024-04-03 21:53 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val signmbti = intent.getStringExtra("userMbti")
지금은 4개의 요소이지만 만약 더 많은 값을 페이지로 이동시켜야한다면 이렇게 매번 하나씩 넣어줘야 할까요??

물론 너무 많은 요소를 이동시키는 것은 지양해야하는 일이긴 합니다. 하지만,  그 방법을 알고있는건 좋겠죠?
Data Class를 만들고, Parcelable을 적용시킨다면 class 자체를 Intent로 이동시킬 수 있습니다!

처음하기에는 꽤나 헷갈리니 나중에 여유로울때 한번 찾아보고 적용해봐요 :)
[관련 링크](https://ducksever.tistory.com/31)

2024-04-03 21:53 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                startActivity(intent)
매번 Intent를 쓰기 귀찮지 않나요??

[Scope 함수](https://haero.tistory.com/21)를 활용해보면 좋을 것 같아요!
불필요한 변수 선언을 줄이고 가독성을 향상시킬 수 있습니다!

2024-04-03 21:53 UTC, chattymin commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +        binding.tvUserMbti.text = "MBTI: $userMbti"
위에 말씀드렸던 Scope 함수중 `with`라는 친구의 활용 방법입니다!

이렇게 사용하면 불필요한 반복도 줄여주고, with(binding) 내부에 있는 코드들이기 때문에 "저 부분은 UI를 조정하는 부분이구나" 라는 느낌을 줘서 다른 사람이 읽기에도 편해집니다 :)

```suggestion
   with(binding) {
        tvUserId.text = "ID: $userId"
        tvUserPw.text = "Password: $userPw"
        tvUserName.text = "Name: $userName"
        tvUserMbti.text = "MBTI: $userMbti"
    }
```

2024-04-03 21:53 UTC, chattymin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            }
`if ~ else if ~ else`이 구조는 좋지 않은 구조입니다.
무언가 추가된다면 else if를 매번 적어줘야해서 유지보수에 좋지않고, 한눈에 코드 파악이 어렵습니다.

그래서 코틀린에서는 `when`을 사용하여 연산할 수 있습니다! [사용법](https://magicalcode.tistory.com/entry/%EC%BD%94%ED%8B%80%EB%A6%B0-%EB%B0%98%EB%B3%B5%EB%AC%B8)을 공부해보고 적용하시는걸 추천드립니다!

2024-04-03 21:53 UTC, chattymin commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/tv_welcome"
id를 조금 더 직관적으로 네이밍 하면 좋을 것 같습니다!!!
activity에서 해당 id값으로 접근을 해야하는데 명확하지 않다면 헷갈릴 수 가있어용

[안드로이드 네이밍 규칙](https://velog.io/@tlsgks48/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%A6%AC%EC%86%8C%EC%8A%A4-%EB%84%A4%EC%9D%B4%EB%B0%8D-%EA%B7%9C%EC%B9%99)을 따라서 작성한다면 모두가 알아보고 유지보수하기 좋은 코드를 작성할 수 있어용~

2024-04-03 21:53 UTC, chattymin commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_width="match_parent"
constraint를 양방향 연결해주고 0dp를 써도 같은 효과를 낼 수 있어요!
start와 end를 연결했다면 width를 0dp로, top과 bottom을 연결했다면 height를 0dp로!

match_parent를 지양하는 코딩을 추천드립니다!
match_parent는 제약조건과 상관없이 작동하기 때문에 ConstraintLayout과는 적합하지 않습니당

2024-04-03 21:53 UTC, chattymin commented on app/src/main/res/layout/activity_main.xml
> +    </ScrollView>
이부분을 스크롤뷰로 한 이유가 있을까요??

2024-04-03 21:53 UTC, chattymin commented on app/src/main/res/layout/activity_main.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
다양한 뷰 써보는것 좋아요~!!!

2024-04-03 21:53 UTC, chattymin commented on app/src/main/res/layout/activity_signup.xml
> +        android:hint="비밀번호를 입력해주세요"
아래에 있는 xml들도 그렇고 전부 string추출을 하는건 어떨까요??

그냥 써도 될텐데 귀찮게 추출하라고하죠 ㅎㅎㅎ
[이런 이유](https://ddioniii.tistory.com/24)들이 있으니 한번 해보시는걸 추천합니다!

2024-04-04 01:42 UTC, junseo511 approved these changes
첫 과제 만만치 않으셨을 텐데 고생 많으셨습니다~~👍👍

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/tv_welcome"
벌써 한번 휩쓸고 가셨군요~~ [PRND 컨벤션](https://github.com/PRNDcompany/android-style-guide) 여기도 참고하기 참 좋습니다 :)

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val signmbti = intent.getStringExtra("userMbti")
저도 처음에 이부분 꽤나 어려웠답니다 🥺 추가적으로 Bundle이 뭔지 알아보셔도 좋을거같아요

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        binding.btnSignup.setOnClickListener {
여기 유난히 엔터가 많이 들어갔다고 생각되지 않나요?!
이러한 부분을 개선할 수 있는 단축키가 있답니다 🤭🤭

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +        // SignUpActivity로부터 전달된 값들을 받아옴
'주석이 필요한 코드는 나쁜 코드이다' 라는 말이 있는거 아시나요?!

충분히 의도를 알 수 있는 코드에서는 주석을 지워주시는 편이 좋습니다~~!!!!

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            }
**[객체 지향 생활 체조 원칙](https://jamie95.tistory.com/99) 제 2항 : else 예약어를 쓰지 않는다**

위 링크 참고하시면 좋을거같아요 👍👍

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/res/drawable/pic.jpg
쿼카가 귀엽군요! pic.jpg 보다는 좀 더 좋은 객체명이 있을 것 같아요!!

네이밍은 항상 개발자의 의도를 보여줄 수 있어야 합니다 😁

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_width="match_parent"
저도 자꾸 이친구를 까먹고 진행하게 되네요 😅

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/res/layout/activity_login.xml
> +        android:text="비밀번호"
하드코딩된 텍스트는 지양하는 편이 좋습니다!!!! 왜 그럴까요? 🤔

2024-04-04 01:42 UTC, junseo511 commented on app/src/main/res/layout/activity_main.xml
> +        android:textSize="30dp"
위의 ID는 sp, PW는 dp로 진행하셨군요!! 코드는 일관성이 중요합니다 :)

dp와 sp의 차이에는 어떤 것이 있을까요?

2024-04-04 05:43 UTC, KwakEuiJin reviewed
효은님 1주차 과제 고생하셨습니다~!! Toast마다 context를 다르게 준 의도가 있는지 궁금하네요ㅎㅎㅎ

2024-04-04 05:43 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            val editpw = binding.pw2.text.toString()
아이디에 숫자를 넣으면 어떤 뷰인지 나중에 헷갈리실걸요! 하핳 효은님 pw78번은 뭐라고 하셨었죠? 처럼요

2024-04-04 05:43 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                startActivity(intent)
요런건 상수로 빼둬야 intent를 다시 활용하는 Activity에서 헷갈리지 않을 것 같네요

2024-04-04 05:43 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                    Toast.LENGTH_SHORT
와우 applicationContext 를 쓰신 이유는 무엇인가요?!

2024-04-04 05:43 UTC, KwakEuiJin commented on app/src/main/res/drawable/btn_color.xml
> +    <solid
solid원칙 중요하죠

2024-04-04 10:12 UTC, chanubc requested changes
처음이라 어려웠을 텐데 너무 고생 많으셨습니다!!
정말 잘하셨어요ㅎㅎ 약간의 리뷰들만 수정해주세요~

2024-04-04 10:12 UTC, chanubc commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/tv_welcome"
저희 자체 미미나 했던 노션 참고하셔서 리팩토링 해주세요!
하단에 reference 첨부했습니다!

2024-04-04 10:12 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                intent.putExtra("userMbti", signmbti.toString())
반복되는 key값들은 상수화 시켜주면 좋아요!!
[const val](https://velog.io/@m0ngj1/Kotlin-var%EA%B3%BC-val-%EC%83%81%EC%88%98%ED%99%94-const-val%EA%B3%BC-val)
보통 최하단 compainon object 블록을 만들고
그안에 상수화를 진행 시켜요!

2024-04-04 10:12 UTC, chanubc commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            if (signid.length < 6 || signid.length > 10) {
```suggestion
            if(signid.length !in 6..10)
```

이런 식으로 kotlin 문법 in을 사용해서 바꿀 수도 있답니다!

2024-04-04 10:12 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                startActivity(intent)
로그인에서 -> 메인 화면으로 간 이후에 로그인 화면으로는 돌아갈 필요가 없으니
startActivity 이후
finish()함수를 추가시켜주면 좋을 것 같아요!

2024-04-04 12:32 UTC, chanubc commented on app/src/main/res/layout/activity_login.xml
> +        android:text="비밀번호"
string 추출 해주시면 좋습니다!

2024-04-04 12:33 UTC, chanubc commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/tvUserName"
xml id를 만들때는 보통 snacke case
tv_user_name 이런식으로 만들어요!

2024-04-04 12:36 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val signmbti = intent.getStringExtra("userMbti")
추후에 Serializable과 parcelable 의 차이를 공부해 보는 것도 좋을것 같아요!
[parcelable vs serializable](https://www.charlezz.com/?p=823)

특히 parcelable 을 편리하게 구현할 수 있는 플러그인도 있습니다
[parcelable plugin](https://www.charlezz.com/?p=44613)

2024-04-05 03:45 UTC, OliviaYJH approved these changes
수고하셨습니다~😊

2024-04-05 03:45 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                    "ID는 6~10글자 사이로 입력해주세요",
string 요소 따로 빼주면 좋을 것 같아요!

2024-04-05 03:45 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            startActivity(intent)
apply 스코프 펑션 사용하면 깔끔할 것 같아요!

2024-04-05 03:45 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            } else if (signpw.length < 8 || signpw.length >12) {
if else문도 좋지만 when문을 사용하는 것도 좋아보여요!

2024-04-05 18:31 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val signmbti = intent.getStringExtra("userMbti")
@chattymin 


//signid, signpw..등등은 SignUpActivity에서 받은 변수명이라고 한다면
@Parcelize
data class signUp_input(
	@SerializedName("signid") val signid : String,
	@SerializedName("signpw") val signid : String,
	@SerializedName("signname") val signid : String,
	@SerializedName("signmbti") val signid : String,
	) : Parceable
	
//SignUpActivity
val intent = Intent(this, LoginActivity::class.java)
intent.putExtra("signUp_input", signup_input)
startActivity(intent)

//LoginInActivity
var intent = intent
var testList = intent?.getParcelableExtra("signUp_input")

그러면 이런식으로 작성해주면 되는걸까요? 틀린 부분이 있다면 검토 부탁드립니다!

2024-04-07 09:20 UTC, cacaocoffee approved these changes
수고하셨어요! 다른분들이 많이 달아둬서 제가 아는한 최대한 알려드리려 노력은 해봤습니다!

2024-04-07 09:20 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            if (signid.length < 6 || signid.length > 10) {
수치 부분들도 상수화 해두면 좋아요!

2024-04-07 09:20 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                ).show()
Snackbar.make 가 반복되고 있어요 해당 부분을 따로 함수화 하면 재사용성이 높아질 수 있을거 같아요

2024-04-07 16:14 UTC, chanubc approved these changes

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val signmbti = intent.getStringExtra("userMbti")
> 저도 처음에 이부분 꽤나 어려웠답니다 🥺 추가적으로 Bundle이 뭔지 알아보셔도 좋을거같아요



> 추후에 Serializable과 parcelable 의 차이를 공부해 보는 것도 좋을것 같아요! [parcelable vs serializable](https://www.charlezz.com/?p=823)
> 
> 특히 parcelable 을 편리하게 구현할 수 있는 플러그인도 있습니다 [parcelable plugin](https://www.charlezz.com/?p=44613)

이해하는데 도움 많이 되었습니다 감사합니다.

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            val editpw = binding.pw2.text.toString()
네!! 변수명 만드는 법을 얼른 공부해야될 것 같습니다

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                startActivity(intent)
오 그렇군요..! 
찾아보니 finsh() 또는 LoginActivity.this.finish() 이런식으로 쓸 수 있겠네요?

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        binding.btnSignup.setOnClickListener {
흠, 코드 정렬은 ctrl+alt+l로 하는데, 그거는 공백까지는 없애주진 않더라구요
제가 찾아본 바로는.. binding.btn..저기 부분을 긁어서 ctrl+shift+화살표 위 해서 올리는 방법인데..
준서님이 생각하신 방법이랑 같을까요?

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +        // SignUpActivity로부터 전달된 값들을 받아옴
네넵 제가 처음에 너무 이해하기 어렵고 헷갈려서 써놓은건데 지우는 것을 깜빡했네요 ㅋㅋㅠㅠㅠ
주석 필요없는 코드 만들기!!

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            if (signid.length < 6 || signid.length > 10) {
넵! 이 리뷰 보고 compose 과제에서는 그렇게 적용해 보았습니다. 감사합니다.

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            } else if (signpw.length < 8 || signpw.length >12) {
네! 이 코리보고나서 compose과제에서 when을 사용해보았습니다. 감사해요.

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                startActivity(intent)
상수로 빼둔다는게 어떤 의미인지 잘 이해가 가지 않습니다...

2024-04-07 17:06 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                intent.putExtra("userMbti", signmbti.toString())
companion object {
    const val USER_ID_KEY = "userId"
    const val USER_PW_KEY = "userPw"
    const val USER_NAME_KEY = "userName"
    const val USER_MBTI_KEY = "userMbti"
}


이런식으로 말씀이신가요?

2024-04-07 17:07 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +        binding.tvUserMbti.text = "MBTI: $userMbti"
신세계네요. 감사합니다!!

2024-04-07 19:03 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                intent.putExtra("userMbti", signmbti.toString())
오 네 맞아요!! 좋습니다 ㅎㅎ

2024-04-08 06:08 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                startActivity(intent)
이해했습니다 ㅎㅎ! companion object 블록 안에 상수화를 시키라는 말씀이셨군요!

2024-04-08 11:48 UTC, junseo511 commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        binding.btnSignup.setOnClickListener {
내일 미미나에서 진행해볼게요~~😄

2024-04-10 15:50 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                startActivity(intent)
with(intent) {
                putExtra("userId", signid.toString())
                putExtra("userPw", signpw.toString())
                putExtra("userName", signname.toString())
                putExtra("userMbti", signmbti.toString())
                }
    startActivity(intent)
    
    이렇게 바꿀 수 있을 것 같은데 맞을까요?

2024-04-10 15:53 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            }
감사합니다. 
이 코리를 보고 compose에서는 when을 적용해보았습니다!

2024-04-10 16:52 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/tv_welcome"
감사합니다! 변수명 바꾸도록 하겠습니다

2024-04-10 16:52 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_width="match_parent"
아.. 그렇군요 감사합니다..

2024-04-10 16:55 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_main.xml
> +    </ScrollView>
그 당시 그림을 원하는 위치에 원하는 크기만큼 두고 싶었는데..
구글링 찾아보다가 스크롤뷰가 남은 여유공간을 모두 차지하는 아이라고 하길래 한 번 써본 것 같습니다..하하;.. 부끄럽네요

2024-04-10 16:55 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_main.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
넵~!

2024-04-10 16:59 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_signup.xml
> +        android:hint="비밀번호를 입력해주세요"
string추출 리뷰 여러번 받았던 내용이네요 
주신 자료 토대로 열심히 써보겠습니다 !

2024-04-10 16:59 UTC, hyoeunjoo commented on app/src/main/res/drawable/pic.jpg
넵!!

2024-04-10 17:01 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_login.xml
> +        android:text="비밀번호"
하드코딩 텍스트를 지양해야 하는 이유는 앱을 다른 언어로 번역하기가 어렵고, 문자열 재사용이 어렵다는 단점 때문인 것 같습니다

2024-04-10 17:04 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_main.xml
> +        android:textSize="30dp"
dp는 픽셀독립의 단위로, 화면의 크기가 달라도 사이즈가 달라지지 않고 동일한 비율로 보여줍니다. UI 레이아웃을 정의할 때 레이아웃의 치수나 위치를 지정하기 위해 쓰입니다.
sp는 TextView의 textSize를 지정할 때 사용합니다.

안드로이드 설정 화면에서 사용자는 안드로이드 시스템 전체에서 보여질 수 있는 텍스트의 크기를 지정할 수 있는데, sp는 해당 설정에 영향을 받습니다.

2024-04-10 17:06 UTC, hyoeunjoo commented on app/src/main/res/drawable/btn_color.xml
> +    <solid
추상적으로 얼핏 알고 있었던 개념인데 이렇게 다시 한 번 말씀해주신 덕분에 오랜만에 찾아보고 기억 상기시킵니다. 감사합니다!

2024-04-10 17:07 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                    Toast.LENGTH_SHORT
당시에 context로 했더니 오류가 떠서 이것저것 찾아보다가 아무 생각 없이 쓴 것 같습니다... 고쳐야할 것 같습니다

2024-04-10 17:07 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            if (signid.length < 6 || signid.length > 10) {
넵! 감사합니다

2024-04-10 17:07 UTC, hyoeunjoo commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/tvUserName"
네이밍 규칙을 잘 따라보도록 하겠습니다

2024-04-10 17:08 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                    "ID는 6~10글자 사이로 입력해주세요",
넵! 적용해보겠습니다

2024-04-10 17:08 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                ).show()
네 함수로 빼보도록 하겠습니다!

2024-04-10 17:11 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            startActivity(intent)
해당 부분을 apply 스코프 펑션을 이용하면

val intent = Intent(this@LoginActivity, SignUpActivity::class.java).apply {
    startActivity(this)
}

이렇게 바꿀 수 있을 것 같습니다.
근데 궁금한 점이 하나 있습니다! 이렇게 한 줄로 쓰이는 문장에서도 apply를 이용하는것을 더 지향하나요?

2024-04-11 00:38 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            startActivity(intent)
저는 개인적으로 한줄로 쓰이는 문장에서는 잘 사용하진 않아요!
이건 사람 바이 사람 인것 같아요

2024-04-11 00:49 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                startActivity(intent)
1. 네네 위와 같이 kotlin 문법을 활용하는 방안이 있고
```kotlin
Intent(this, NextActivity::class.java).apply {
    putExtra("userPw", signpw.toString())
    putExtra("userName", signname.toString())
    putExtra("userMbti", signmbti.toString())
}.also {
    startActivity(it)
    finish()
}
```
2. 말씀하신대로 finish()만 붙여도 좋아요!
```kotlin
val intent = Intent(this, NextActivity::class.java).apply {
    putExtra("userPw", signpw.toString())
    putExtra("userName", signname.toString())
    putExtra("userMbti", signmbti.toString())
}
startActivity(intent)
finish()
```

이정도 문법은... 전 개인 적으로 코드 작성자의 취향차이라고 생각합니다!
나중에는 1번식을 많이 볼수 도 있겠지만 초반에 코틀린 문법이 익숙치 않으면 2번식으로 쓰는게 더 낫다고 생각해요!
저도 사실 아직 2번 형태가 더 편합니다ㅎㅎ

2024-04-11 00:55 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            startActivity(intent)
> 해당 부분을 apply 스코프 펑션을 이용하면
> 
> val intent = Intent(this@LoginActivity, SignUpActivity::class.java).apply { startActivity(this) }
> 
> 이렇게 바꿀 수 있을 것 같습니다. 근데 궁금한 점이 하나 있습니다! 이렇게 한 줄로 쓰이는 문장에서도 apply를 이용하는것을 더 지향하나요?

그리고 apply는 주로 초기화를 담당하기 때문에 **intent에 데이터를 집어 넣는 putExtra에 활용하면 좋지만**
**startActivity와 같이 작업 실행시키는 구문은 적합하지 않다**고 생각합니다!


startActivity의 경우 apply 블록 밖에다 작성하거나 also나 let을 통해 작성하는게 맞다고 생각해요!

2024-04-11 00:55 UTC, chanubc commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                    "ID는 6~10글자 사이로 입력해주세요",
alt+enter 누르면 extract string resource라고 아마 뜰겁니다!

2024-04-11 02:09 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                startActivity(intent)
정성스러운 답변 너무 감사합니다

2024-04-11 02:11 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                    "ID는 6~10글자 사이로 입력해주세요",
헐. 저 다 지우고 막 하나하나 추출하고 있었는데..........
감사합니다ㅜㅜ

2024-04-11 02:14 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            startActivity(intent)
오..! 답변 감사합니다!

2024-04-11 02:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                    "ID는 6~10글자 사이로 입력해주세요",
![image](https://github.com/NOW-SOPT-ANDROID/hyoeun-joo/assets/106955456/3332f190-35bb-44ff-a3f3-369395dad25e)

1. 텍스트 부분에 커서 놓고 alt + 엔기
2. 왼쪽 전구 아이콘 누르기

둘 중 하나로 하시면 아마 extract string resource라 뜰거에요!

2024-04-11 17:11 UTC, chanubc approved these changes
고생 많으셨습니다!!ㅠㅠ 진짜 금방 일취월장 하시네요. 놀랏습니다
나머지 부분은 다음과제에서 차차 해보는 걸루 해요~

2024-04-11 17:11 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val signPw = userData?.getUserSignUpPw()
```suggestion
        val signId = userData?.userId
        val signPw = userData?.userPW
```
요친구들만 이렇게 사용하면 될것 같아요!
data class에 선언된 변수들을 그대로 가져와서 쓰시면 됩니다.
굳이 return함수 만들 필요는 없어요!

data class의 내부 함수에 값을 return하는 형태는 아마 추후에 쓰일테니 알아둬 두시기만 하면 됩니다!

2024-04-11 17:11 UTC, chanubc commented on app/src/main/java/com/sopt/now/SignUpData.kt
> +    }
요부분은 지금은 필요 없을거어ㅔ요!

2024-04-11 17:11 UTC, chanubc commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +    }
compaion object를 보통 최하단에 위치시킵니다!!
sjhowSnackBar랑 위치를 변경해주시면 될것 같아요

2024-04-11 18:19 UTC, merged

2024-04-11 18:20 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +    }
넵!