Feat/week xml 02
NOW-SOPT-ANDROID/hyoeun-joo pull request #6
Opened 2024-04-16 14:32 UTC by hyoeunjoo

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #5  

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
-  리스트 위에 기존 Friend형식과는 다른 내 프로필을 디자인하기
-  리스트 상단에 위치하게 하기
-  데이터는 최소 스크롤이 가능하게 하기
-  스크롤 시, 내 프로필 또한 같이 스크롤 되게 하기

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/hyoeun-joo/assets/137873124/bb7c9b2c-87fc-4f0f-9045-87a75450e70c

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
하하.. 도움 주신 분들 정말 많으신데.. 정말 감사의 말씀 드립니다
이것만 거의 일주일 가량을 붙들고 있었습니다(놀라지마세요).. 어렵네요ㅠㅠ
부족한 부분들 많이 많이 알려주시면 정말 감사하겠습니다!!!

2024-04-18 00:46 UTC, junseo511 reviewed
헉,,, 리뷰를 달다보니 엄청나게 달아버렸네요!! 가능하신 부분만 반영하시면 될듯합니다 :)

근데 이게 와비의 코드,,,?! 성장속도가 상당하신걸요 👏👏

2024-04-18 00:46 UTC, junseo511 commented on app/build.gradle
> +    implementation 'androidx.fragment:fragment-ktx:1.6.2'
fragment 친구가 겹치네요!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +    }
```suggestion
    override fun onDestroyView() {
        _binding = null
        super.onDestroyView()
    }
```

많은 오비분들이 리뷰 달고 다니실거같은데!! 이쪽이 메모리 누수에 안정적이라고 하네요 😄

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Friend/FriendData.kt
> +    @DrawableRes val profileImage: Int,
Coil과 Glide가 뭔지 아시나요?

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Home/HomeViewModel.kt
> +    )
이러면 어떤 아이디로 로그인해도 주효은님이 될텐데!!

열심히 만들어둔 로그인 정보에 있는 이름으로 추가되도록 해보면 어떨까요?!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +        val concatAdapter = ConcatAdapter(userAdapter, friendAdapter)
ConcatAdapter 잘 쓰셨군요! 좋습니다

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        Log.d("IntentData", "fragment data: $signId")
불필요한 로그는 지워주시는게 좋습니다!!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/MainActivity.kt
>          }
함수로 분리해보는건 어떤가요?

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/MainActivity.kt
>          }
이친구는 함수가 이미 있네요!!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +
줄바꿈이 두줄인데, 정리하는 단축키가 있지 않았나요?!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/User/UserAdapter.kt
> +//        holder.bind(userData)
불필요한 주석은 지워주세요!!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/User/UserAdapter.kt
> +        notifyDataSetChanged()
혹시 DiffUtil을 아시나요? notifyDataSetChanged와 차이점이 뭘까요?

[위의 질문과 이 질문에 도움이 될만한 링크](https://ranseo.tistory.com/246)를 들고왔습니다!!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/User/UserAdapter.kt
> +class UserAdapter() : RecyclerView.Adapter<UserAdapter.UserViewHolder>() {
Adapter에도 종류가 있는 것 아시나요?

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/User/UserAdapter.kt
> +                tvSelfDescription.text = "34기 YB 주효은입니다!!!"
이미 데이터에 소개가 있던 것 같은데,,,! 더 예쁘게 넣어볼 수 있답니다

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="0dp"
0dp 활용 좋군요 👍

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/res/layout/fragment_my_page.xml
> +
두 줄이 띄워져있네요!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/res/layout/item_friend.xml
> +        android:maxLines="3"
3줄이 넘어가는데 갑자기 잘려보인다면 이상하겠죠? [ellipsize](https://minchanyoun.tistory.com/9)를 아시나요?

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/res/layout/item_user.xml
> +        android:src="@drawable/pic"
pic이라는 drawable 이름만으로 어떤 사진인지 알 수 있을까요?

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/res/layout/item_user.xml
> +        android:layout_marginVertical="15dp"
[안드로이드에서 홀수 dp는 지양하는게 좋습니다!](https://dev-ahn.tistory.com/163) 왜일까요?

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/res/menu/menu_home.xml
> +        android:title="홈" />
하드코딩된 text는 빼주는게 좋을거같아요!!

2024-04-18 00:46 UTC, junseo511 commented on app/src/main/res/values/strings.xml
> +
비슷한 자기소개가 여러곳에서 사용되고 있네요!!

2024-04-21 04:22 UTC, OliviaYJH approved these changes
수고했어요😊

2024-04-21 04:22 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +    }
오 이거는 몰랐네요! 저도 수정해야겠어요!

2024-04-21 04:22 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                Log.d("IntentData", "User data: $userData")
여기 로그도 불필요해보여서 삭제해도 좋을 것 같아요!

2024-04-21 04:22 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +                    replaceFragment(myPageFragment)
scope function을 사용하면 더 깔끔하게 작성할 수 있을 것 같아요! 
```suggestion
                   replaceFragment(MyPageFragment().apply {
                        arguments = Bundle().apply {
                            putParcelable("userData", userData)
                        }
                    })
```
이런 식으로요!

2024-04-21 04:22 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +                    bundle.putParcelable("userData", userData)
여기서 putParcelable의 key로 "userData" 말고 아래에 companion object로 생성한 INTENT_USER_DATA 스트링 사용하면 될 것 같아요!

2024-04-21 12:18 UTC, chanubc requested changes
어려웠을 텐데 정말 잘하셨습니다!!
실력이 금방금방 느시네요

몇가지 수정사항은 반영해주세요!

2024-04-21 12:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +    ): View? {
onCreateView에서는 View를 반환해야 하기 때문에 non null타입로 지정해주세요! 
View뒤에 "?"를 지우시면 됩니다!

2024-04-21 12:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +    private val viewModel by viewModels<HomeViewModel>()
요것도 위치가 최상단으로 올라가면 좋아요!
전역 변수끼리 묶어서 보는게 가독성에 더 좋을 것 같습니다

2024-04-21 12:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +    }
공식문서에서는 상단의 코드로 나오기는 합니다.

수명주기 메소드를 호출한 다음에 변수를 null 처리 하는 것이 저는 좀더 낫다고 생각해요!

2024-04-21 12:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/User/UserAdapter.kt
> +                tvSelfDescription.text = "34기 YB 주효은입니다!!!"
이것도 수정해주세요!

2024-04-21 13:47 UTC, cacaocoffee approved these changes
셤기간이라 바쁜데도 수고했어요!

2024-04-21 13:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +
공백이 2줄이야!

2024-04-21 13:47 UTC, cacaocoffee commented on app/src/main/res/layout/fragment_my_page.xml
여기 페이지에는 이름에 대한 컨벤션이 다른거 같아요 다른 곳에선 tv_ 였다면 여기만 _가 없어서 통일감을 주면 좋을것 같아요

2024-04-28 13:15 UTC, hyoeunjoo commented on app/build.gradle
> +    implementation 'androidx.fragment:fragment-ktx:1.6.2'
앗 그렇네요

2024-04-28 13:23 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/Friend/FriendData.kt
> +    @DrawableRes val profileImage: Int,
Android Kotiln 애플리케이션의 이미지 로딩을 위해 쓰입니다. 

Coli (Coroutine Image Loader)는 Kotlin Coroutines로 만들어진 Android  백엔드 이미지 로딩 라이브러리 입니다. 메서드 수와 크기가 작아 Glide보다 가볍습니다. 

Glide는 원래 Java기반이지만 Kotlin을 지원합니다. Coil에 비해 기본적으로 더 많은 이미지 형식을 지원합니다. GIF 및 애니메이션 이미지에 대한 지원이 향상되었습니다. 최적화를 위한 많은 옵션을 제공하지만 Coil에 비해 더 많은 사용구 코드가 필요할 수 있습니다.

2024-04-28 13:24 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/Home/HomeViewModel.kt
> +    )
하하 맞습니다..ㅎㅎ 급해서 이렇게 했네요.. 바꿔보겠습니다!

2024-04-28 13:24 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +        val concatAdapter = ConcatAdapter(userAdapter, friendAdapter)
감사합니다 ~.~ 어려웠습니다..

2024-04-28 14:16 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +    ): View? {
아하..! 넵 감사합니다

2024-04-28 14:16 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/Home/HomeFragment.kt
> +    private val viewModel by viewModels<HomeViewModel>()
그렇겠네요. 감사합니다!

2024-04-28 14:16 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/MainActivity.kt
>          }
아 그렇네요.. 제대로 코드를 보지 않고 세미나 코드를 복붙한 저를 반성합니다ㅠㅠ

if (currentFragment == null) {
     replaceFragment(HomeFragment())
     }
로 바꿀 수 있겠네요

2024-04-28 14:16 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +                    bundle.putParcelable("userData", userData)
감사합니다!!!

2024-04-28 14:16 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +                    replaceFragment(myPageFragment)
미쳤다.. scope의 여신.. 신.. 감사합니다.

2024-04-28 14:16 UTC, hyoeunjoo commented on app/src/main/res/layout/item_user.xml
> +        android:src="@drawable/pic"
profile, user_profile등으로 바꾸는게 좋을 것 같습니다

2024-04-28 14:38 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +
ctrl Alt L 입니다

2024-04-28 14:38 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/User/UserAdapter.kt
> +                tvSelfDescription.text = "34기 YB 주효은입니다!!!"
넵 string으로 빼뒀던걸로 넣겠습니닷

2024-04-28 14:38 UTC, hyoeunjoo commented on app/src/main/res/layout/item_friend.xml
> +        android:maxLines="3"
아하..!! 감사합니다!! 
사실 3줄로 한 것은 임시방편이었던게 맞습니다 ^^...

저는 3줄이 넘어가면 뒤에 ...이 보였으면 하므로
android:ellipsize = "end"
android:singleLine="true" 를 넣어주면 되겠군요

2024-04-28 14:38 UTC, hyoeunjoo commented on app/src/main/res/layout/item_user.xml
> +        android:layout_marginVertical="15dp"
첨부해주신 글을 읽어보니, 1dp 단위로 작업할 경우, hdpi일 때 픽셀 환산 소수점이 발생한다고 합니다. 물리적 픽셀에는 소수점이 존재하지 않아, 2dp의 배수로 제작을 염두에 두어야 깔끔하게 디자인 제작이 가능하다는 장점이 있다고 합니다.  

관련 단락의 마지막 부분에 hdpi를 사용하는 단말이 거의 존재하지 않을 때는 고려하지 않아도 좋다는 말이 있길래 질문 드립니다. 근래에는 hdpi 디스플레이를 가진 기기가 적은 걸로 알고 있습니다. 그래도 넓은 범위의 기기를 지원하기 위해 계속 짝수dp를 사용하는게 좋을까요?

2024-04-28 14:38 UTC, hyoeunjoo commented on app/src/main/res/values/strings.xml
> +
이 부분 활용하겠습니다~

2024-04-29 13:10 UTC, chanubc approved these changes
브랜치 protection 추가해주세요!

2024-04-29 17:26 UTC, chanubc approved these changes

2024-05-01 17:14 UTC, merged