Feat/week xml 04
NOW-SOPT-ANDROID/hyoeun-joo pull request #9
Opened 2024-05-03 09:51 UTC by hyoeunjoo

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
* 회원 가입 로직 구현
* 로그인 로직 구현
* 데이터를 받아와서 MyPageFragment 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/hyoeun-joo/assets/137873124/46d25b08-80b1-47cc-ab42-6b8ea340fa0a

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
서버 통신.. 많이 낯서네요 하하
아직 코드도 많이 더럽고, 넣지 못한 내용들도 많습니다ㅠㅠ 얼른 리팩할 생각입니다.
많이 지적해주시면 감사하겠습니다.

2024-05-05 07:25 UTC, librarywon commented
안녕하세요 효은님 반갑습니다 😄  저는 32,33기 안드로이드를 수료한 명예 OB 서재원이라고합니다.

영광스럽게도 효은님 리뷰어를 맡게 되었는데 제가 생각하는 코드리뷰는 "상호 의견을 나누면서 서로 성장하는 것"이라고 생각해요!

제가 아는 선에서 최대한 의견을 제시볼테니 **제 의견이 무조건 맞지 않다는 것**을 염두하고 리뷰를 확인해주시면 좋을 것 같습니다

과제 하느라 수고하셨습니다

2024-05-05 07:43 UTC, hyoeunjoo commented
> 안녕하세요 효은님 반갑습니다 😄 저는 32,33기 안드로이드를 수료한 명예 OB 서재원이라고합니다.
> 
> 영광스럽게도 효은님 리뷰어를 맡게 되었는데 제가 생각하는 코드리뷰는 "상호 의견을 나누면서 서로 성장하는 것"이라고 생각해요!
> 
> 제가 아는 선에서 최대한 의견을 제시볼테니 **제 의견이 무조건 맞지 않다는 것**을 염두하고 리뷰를 확인해주시면 좋을 것 같습니다
> 
> 과제 하느라 수고하셨습니다

안녕하세요!! 제 코드리뷰를 해주신다니 저는 정말 너무 영광입니다..
제가 부족한 부분이 많습니다.  남겨주시는 리뷰들 저도 검색해보고 공부하면서 많이 배우고 싶습니다! :) 
시간 내어주셔서 감사합니다 !!

2024-05-05 08:05 UTC, librarywon commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"></activity>
`</activity>` 코드는 제거해주어도 무방할 것 같네요

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        savedInstanceState: Bundle?,
왜 마지막에 ,(콤마)를 붙여도 되는걸까요?

코틀린에 재밌는 문법인 `트레일링 콤마`가 무엇인지 확인해보시면 좋을 것 같습니다.

아래 공식문서를 첨부해둘게요

https://kotlinlang.org/docs/coding-conventions.html

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        Log.d("MyPageFragment", "userId: $userId")
userId가 잘 넘어오는지 확인하는 용도로 적어주신 것 같은데 

로그 코드는 지워주는 것이 좋다고 생각합니다 불필요한 로그 호출을 제거해서 깔끔한 코드를 작성하는 것을 선호하거든요

에러가 발생했을 때 해당 에러를 로그로 찍는 것은 괜찮다고 생각합니다.

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        ServicePool.authService.getUserInfo(userId.toInt())
이렇게 `userId`를 정수형으로 변환하는 과정이 있다면 처음부터 Int값으로 값을 넘기는 것이 좋지 않을까요?

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        viewModel = ViewModelProvider(this).get(LoginViewModel::class.java)
`ViewModelProvider`를 사용하셨군요 다른 코드를 보시면 뷰모델을 생성할 때 `by viewModels()`를 사용한 코드를 보실 수 있을 것 같은데 어떤 차이가 있는지 확인을 해보시는 것도 좋지 않을까 싶습니다.

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    private lateinit var viewModel: LoginViewModel
코틀린에서 늦은 초기화 방식에는 `lateinit` 과 `by (~~)`이 있는데요 어떤 차이와 장단점이 있는지 한 번 알아보시면 도움이 많이 될 것 같습니다.

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    private fun observeLoginViewModel() {
함수 이름에 함수의 대상과 목적을 제시해주셨군요, 하지만 자세히보면 이 함수가 두가지 역할을 하는 것 처럼 보이는데요

객체지향의 단일 책임 원칙에 따라서 하나의 함수는 하나의 일을 명확하게 해내는 것이 중요합니다.

그래서 함수가 어떤역할을 하는지 바로 알 수 있는 네이밍을 짓는 것도 중요하구요. 

함수길이가 길어져도 좋습니다 그 함수를 명확하게 표현할 수 있다면요

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +
불필요한 공백은 지워주시는 것이 좋을 것 같습니다

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        })
```suggestion
viewModel.loginResult.observe(this) { success ->
    if (success) {
        viewModel.userId.value?.let { userId ->
            val intent = Intent(this@LoginActivity, MainActivity::class.java).apply {
                putExtra("userId", userId)
            }
            startActivity(intent)
            finish()
        }
    }
}
```
코틀린의 `트레일링 람다`를 사용하면 이렇게도 코드를 작성할 수 있습니다.

람다가 무엇인지를 먼저알고 왜 저렇게 변하는지 아는 것도 중요할 것 같네요

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                    finish()
화면을 이동하는 이 로직이 과연 `observeLoginViewModel()`함수 안에 존재하는 것이 맞을까요?

화면 이동하는데 에러가 발생했을 때 observeLoginViewModel() 전체를 뒤져가면서 어디가 문제인지 찾는 상황이 발생할 것 같네요

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    private lateinit var viewModel: LoginViewModel
(~~)는 일부러 안적었습니다 ㅋㅋ

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        )
```suggestion
        return RequestLogInDto(
            authenticationId = binding.etId.text.toString(),
            password = binding.pw2.text.toString()
        )
```
선호에 따라 다르겠지만 굳이 변수를 새로 할당해서 값을 넘겨주는 필요가 있을까 생각이 듭니다.

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginViewModel.kt
> +class LoginViewModel : ViewModel() {
코드리뷰를 하던 도중 뷰모델이 생겼네요 andorid의 AAC viewModel이 MVVM 패턴에서 어떤 역할을 하는지 관심을 가지고 코드를 작성하시면 좋을 듯 싶습니다!

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/LoginViewModel.kt
> +                    }
위에 있는 `MutableLiveData<String>`자료형을 가진 `userId`와 동일한 이름을 가지고 있는 변수가 존재하네요

코드를 읽거나 사람과 컴파일러도 혼동을 줄 수 있으니 수정이 필요해보입니다.

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +    private fun initViews() {
함수 분리를 하려고 노력한 흔적이 보이네요 👍 

뷰를 초기화하는 뷰가 하나라서.. `initView()`가 맞지 않을까..싶긴한데 이건 좀 투머치 확장성을 대비했다는 큰그림(?)

2024-05-05 08:05 UTC, librarywon commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +            phone = phoneNumber
위와 동일한 리뷰를 드릴 수 있을꺼 같아요

2024-05-05 08:05 UTC, librarywon commented on app/src/main/res/layout/activity_signup.xml
> +        android:text="Phone Number"
string 추출을 해두신걸 다시 롤백하셨네요? 하드코딩은 지양하는 것이 좋습니다.

2024-05-05 08:05 UTC, librarywon commented on app/src/main/res/layout/fragment_my_page.xml
> +        android:id="@+id/tv_UserId"
id를 배정할 때 다른화면에서 userId를 사용하는 textView를 사용하면 어떤 문제가 발생할까요?

문제가 발생한다면 어떻게 피할 수 있을지 고민해보시면 좋을 것 같습니다.

2024-05-05 12:10 UTC, OliviaYJH approved these changes
수고하셨습니다!

2024-05-05 12:10 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        userId = arguments?.getString("userId")
계속 사용되는 userId를 따로 빼내도 좋을 것 같아요!

2024-05-05 12:10 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +        Log.d("main","$userId")
불필요한 로그는 지워도 될 것 같아요!

2024-05-05 12:50 UTC, chanubc requested changes
서버통신 처음하면 엄청 어려운데 잘하셨네요!!
고생많으셨습니다~

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
>          return binding.root
이미 View 타입이 초기화 이후 binidng.root를 반환하기 때문에 non null 타입으로 지정해주세요!
"
```suggestion
    ): View {
        _binding = FragmentMyPageBinding.inflate(inflater, container, false)
        return binding.root
```

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    private lateinit var viewModel: LoginViewModel
ㅋㅋㅋㅋㅋㅋ 적어주세요

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +                    val userId = intent.getStringExtra("userId")
userId가  onCreate시에도 먼저 불러오는데 두번 intent.getStringExtra를 사용하신 이유가 있을까요?

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        userId = arguments?.getString("userId")
반복되는 키 값은 상수화 해주세요!

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        userId = arguments?.getString("userId")
sharedPreference로 값을 저장하거나
로그인 시 싱글톤으로 오브젝트 안에 userId 값을 할당하여 앱 전역적으로 사용하는 방법이 있을 것 같습니다!

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +                        userProfile?.let {
null 체크 좋네요!!

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/LoginViewModel.kt
> +    val userId: MutableLiveData<String> = MutableLiveData()
baking property 적용해주세요! 아마 다음주에 배울겁니다
[backing property](https://yoon-dailylife.tistory.com/45)

```suggestion
private val _loginResult = MutableLiveData<Boolean>()
val loginResult: LiveData<Boolean> get() = _loginResult

private val _errorMessage = MutableLiveData<String>()
val errorMessage: LiveData<String> get() = _errorMessage

private val _userId = MutableLiveData<String>()
val userId: LiveData<String> get() = _userId
```

값을 할당할때는 
```kotlin
_loginReult.postValue(true) // 혹은
_loginReult.setValue(true)
_userId.value = "" 
```

3가지 방법이 있는데 차이점을 알아보는 것도 좋습니다! (아마 다음주에..)

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +                viewModel.userId.value?.let { userId ->
sginUpResult가 userId까지 포함하도록 data class를 하나 만들어서
해당 타입을 LiveData의 타입으로 가져가면 더 효율 적일 것 같아요!

2024-05-05 12:50 UTC, chanubc commented on app/src/main/java/com/sopt/now/api/ApiFactory.kt
> +}
시간 나시면 loggingInterceptor도 적용해 보세요!
[logging interceptor](https://velog.io/@hxeyexn/Android-OkHttp3-Logging-Interceptor%EB%A1%9C-%ED%86%B5%EC%8B%A0-%EC%83%81%ED%83%9C-%ED%99%95%EC%9D%B8-%ED%95%98%EA%B8%B0)

2024-05-05 12:50 UTC, chanubc commented on app/src/main/res/layout/activity_signup.xml
> +        android:text="Phone Number"
지난 과제 까지 mbti였다가 전화번호로 변경되는 바람에 급히 수정하신듯 하네요(저도 그랬습니다)ㅎ

2024-05-05 13:34 UTC, cacaocoffee approved these changes
4주차 과제도 수고하셨습니다!

2024-05-05 13:34 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/LoginViewModel.kt
> +                    val error = response.message()
val error 는 사용이 되지 않는 변수로 보여요 수정이 필요해보입니다
response.errobody 쪽 살펴보시면 수정 방안을 금방 찾을 수 있을거예요

2024-05-05 13:34 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/Home/MyPageFragment.kt
> +        savedInstanceState: Bundle?,
한번도 생각 못해본 부분이였는데 덕분에 `트레일링 콤마` 에 대해서 공부하구 가요

2024-05-24 11:26 UTC, chanubc approved these changes

2024-05-24 11:27 UTC, merged